"""
Gemini 2.0 Flash integration — generates plain-English explanations,
fix reasoning, risk, and confidence for each detected issue.
"""

import json
import streamlit as st

try:
    import google.generativeai as genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False


def _get_model():
    api_key = st.secrets.get("GEMINI_API_KEY", "")
    if not api_key:
        return None
    genai.configure(api_key=api_key)
    return genai.GenerativeModel("gemini-2.0-flash")


def enrich_issue_with_ai(issue: dict) -> dict:
    """
    Calls Gemini to add explanation, risk, and confidence to an issue dict.
    Returns the issue unchanged (with ai_* fields populated) if AI unavailable.
    """
    if not GEMINI_AVAILABLE:
        return _fallback(issue)

    model = _get_model()
    if model is None:
        return _fallback(issue)

    prompt = f"""
You are a senior data analyst reviewing a data quality issue.

Issue detected:
- Title: {issue['title']}
- Column: {issue['column']}
- What was found: {issue['detected']}
- Suggested fix: {issue['recommended_fix']}
- Severity: {issue['severity']}

Respond ONLY with a valid JSON object, no markdown, no preamble, with these exact keys:
{{
  "explanation": "2-3 sentence plain English explanation of why this is a problem and what likely caused it",
  "risk": "1-2 sentences on what will go wrong in analysis if this is ignored",
  "confidence": "High or Medium or Low — how confident you are the suggested fix is correct"
}}
"""

    try:
        response = model.generate_content(prompt)
        text = response.text.strip()
        # Strip markdown fences if present
        text = text.replace("```json", "").replace("```", "").strip()
        parsed = json.loads(text)
        issue["ai_explanation"] = parsed.get("explanation", "")
        issue["ai_risk"] = parsed.get("risk", "")
        issue["ai_confidence"] = parsed.get("confidence", "Medium")
    except Exception as e:
        issue = _fallback(issue)

    return issue


def _fallback(issue: dict) -> dict:
    """Generic fallback when Gemini is unavailable."""
    issue["ai_explanation"] = (
        "AI explanation unavailable — check your GEMINI_API_KEY in Streamlit secrets. "
        "The detected issue and recommended fix above are generated by the rule-based engine."
    )
    issue["ai_risk"] = "Risk assessment unavailable without AI."
    issue["ai_confidence"] = "N/A"
    return issue
